### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by JVS23** [ruusukivi/tiralabra#1]
Tiedostot ladattu 20/08/2022, klo 06:00.

# Kokemus Alpha 0.3- releasen jar-tiedostolla testatessa:

Ohjelman käynnistäminen ohjeita noudattaen meni hyvin, ja sillä uuden kartan luominen sekä tutkiminen
luonnistui sujuvasti, ja Dijkstran algoritmi vaikuttaisi toimivan. Käyttöliittymä selkeä, ainoa asia
mikä jäi alussa hieman mietityttämään oli "tunneleiden" määrän ja pituuden määrittely, sillä kyseisen
käsitteen merkitys ei ollut heti alusta dokumentaatiotietojen perusteella tuttu. Sovellusta testaillessani
sain kuitenkin ymmärrettyä näiden tunneleiden merkityksen.

# Kokemus uusimman version kloonaamisella 20/08/2022 commitista:

Gradlella testien runnaaminen toimi erinomaisesti, ja testit menevät läpi + checkstylessä lähinnä pieniä
ja nopeasti korjattavia indentaatiovirheitä ja muita vastaavia. Testikattavuus hyvä. Gradlella itse sovelluksen runnaamisessa tulee itselläni consoleen hieman erikoisia tulostuksia:

![gradlepic](https://user-images.githubusercontent.com/74061917/185730643-f7730e50-59ae-41df-8ab8-ddf2c49854eb.png)

Itse sovellus kuitenkin toimii kuten pitääkin. Tuokin voi tosin olla jostakin omasta systeemistäni kiinni (Win10, perus cmd). Tästä ei tosin haittaa sillä lopullisen sovelluksen voi varmaankin runnata jar-tiedostosta. Dijkstra toimii tässäkin hyvin, JPS ilmeisesti vielä hieman keskeneräinen.

Itse koodi näyttää mielestäni hyvin selkeältä, ja projektihakemisto hyvin rakennetulta, vaikkakin 
"main/java/" kansioista toinen vaikuttaisi olevan hieman redundantti. Koodin dokumentointi erinomaista. En löydä koodista
oikeastaan mitään paranneltavaa, hyvältä näyttää!

Tässä vielä muutama huomio:

1. Projekti menee solmuun joistakin arvojen syötöistä, kuten tunneleiden määrä: 500 maksimipituudella 1, joten näille voisi asettaa jotkin toimivat ääriarvot esim. vahvistukset että syötetyt arvot ovat tiettyjen parametrien välillä.

2. Ui:ssa suositeltu 100x100-koko kartalle on melko iso, sitä oli mielestäni 2k-näytölläkin melko vaikea lukea, joten itse päädyin
testaamaan sovellusta enimmäkseen 50x50-koolla. Suosittelisin ainakin kokeilemaan joitakin eri parametrejä jos joku niistä olisi ensikertaa
sovellusta käyttävälle selkolukuisempi.

Kaikenkaikkiaan erinomainen projekti, ja commandlinellä karttojen rakentelu onnistuneesti on jo itsessään mielestäni kunnioitettava suoritus, jatka samaan malliin! Pahoittelut myös hieman myöhäisestä arvioinnista, kovalevyni sanoi itsensä irti keskellä viikkoa :D

**Comment by ruusukivi** [comment]
Kiitos paljon arvioinnista ja palautteesta! 

Olen painiskellut JPS:n kanssa enkä ehtinyt katsoa näitä ajatuksella läpi. Nimesin tunnelit poluiksi. Laitoin karttojen suositusarvot vähän pienemmiksi - varsinaiset vertailut isommilla kartoilla tehdään ilman ruudulle piirtoa. Lisäksi täydensin dokumentaatiota niin että gradle käynnistyy ilman lisähähöjä (./gradlew -q --console plain run) 

Virheensietoisuutta en vielä lisännyt, koska JPS edelleen kesken. Palaan siihen jos suinkin ehdin.
