### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by mkkarl** [ruusukivi/tiralabra#2]
Repositorio ladattu 26.8. klo 10.12

Jaria ei taida vielä olla, joten sen ehkä voisi poistaa käyttöohjeista, kunnes Jar on luotu. En myöskään saanut käynistettyä ohjelmaa terminaalissa (kansiossa tiralabra-main) ohjeen mukaan ainakaan niin, että ruudulle olisi mitään tekstiä tulostunut. Vaikutti aivan siltä kuin taustalla olisi jäänyt jokin luuppi pyörimään mutta ruudulle ei olisi tulostunut mitään. VS Codella ohjelma kuitenkin käynnistyi ja vaikutti toimivalta.

Yksikkötesteissä on 5 virhettä, joista 4 koskee käyttöliittymää. Käyttöliittymää ei dokumentaatio-ohjeistuksen mukaan tarvitse testata yksikkötesteillä, joten käyttöliittymän rajaamista yksikkötestien ulkopuolelle kannattaa ehkä harkita. Tämä on mahdollista Jacocon määrityksissä. Ohjeet tämän määrittämiseen löytyy esimerkiksi [täältä](https://ohjelmistotuotanto-hy.github.io/java/tehtavat1) kohdasta *13. Parempi testauskattavuus*.

Koodi on selkeästi kirjoitettua.

Toteutusdokumentissa ilahdutti erityisesti laajasti kerrotut lähteet.

**Comment by ruusukivi** [comment]
Kiitos palautteesta! 

_Jaria ei taida vielä olla_

Jar oli ladattu releasen oheen, täytyy lisätä tuo linkitys vielä selkeämmin dokumentaatioon.
https://github.com/ruusukivi/tiralabra/releases/

_En myöskään saanut käynistettyä ohjelmaa terminaalissa (kansiossa tiralabra-main) ohjeen mukaan ainakaan niin, että ruudulle olisi mitään tekstiä tulostunut._ 

Hmmm. Mitään erroria ei tullut näkyville? Itselläni ja edellisellä palautteenantajalla on toiminut ongelmitta. Voisikohan olla joku versioyhteensopivuusongelma? 

Pitää koittaa itsekin kokeilla vielä kloonata ja käynnistää.

Itsellä Gradlesta seuraava versio:
------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------
Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103
Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18.0.1.1 (Homebrew 18.0.1.1+0)
OS:           Mac OS X 12.5.1 x86_64

_Yksikkötesteissä on 5 virhettä, joista 4 koskee käyttöliittymää._

Jep, painiskelen edelleen JPS:n kanssa ja priorisoin noiden fiksauksen pienemmälle prioriteetille. Virheet johtuvat siitä että käyttöliittymä on vähän muuttunut ja testit lukevat vääriä rivejä.

_Koodi on selkeästi kirjoitettua._

Kiitos ☺️
